### ISSUE TITLE
Y=-30000000 + falling = ejected from server

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#2127]
There is an issue where if you are teleported to that coordinate and drop, you get kicked from the server. However, you can rejoin. It is still an annoyance, and allows players to effectively kick each other.

**Comment by Gusted** [comment]
Fixed

**Comment by Wild1145** [comment]
@Gusted What Commit was this fixed in? I dont see a PR or Commit for the patch?

**Comment by ncurran02** [comment]
@Wild1145, it was patched in custom TFM.

**Comment by Wild1145** [comment]
@Focusvity Okay, thats not at all useful here... If its not patched on this Repo the issue is still valid.
